/*
小红书AD

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xiao_hong_shu_ad_go

import (
	"github.com/wenxtech/xiao_hong_shu_ad_go/api"
	"github.com/wenxtech/xiao_hong_shu_ad_go/middleware"
)

type Client struct {
	ApiClient *api.APIClient
}

func Init(cfg *api.Configuration) *Client {
	client := &Client{
		ApiClient: api.NewAPIClient(cfg),
	}
	client.ApiClient.Use(
		middleware.AuthMiddleware,
		middleware.HeaderMiddleware,
		middleware.LogMiddleware,
	)
	return client
}
// API Services
func (c *Client) JgAccountAdOrderInfoAPI() *api.JgAccountAdOrderInfoAPIService {
	return c.ApiClient.JgAccountAdOrderInfoAPI
}
func (c *Client) JgAccountBudgetInfoAPI() *api.JgAccountBudgetInfoAPIService {
	return c.ApiClient.JgAccountBudgetInfoAPI
}
func (c *Client) JgAccountOrderInfoAPI() *api.JgAccountOrderInfoAPIService {
	return c.ApiClient.JgAccountOrderInfoAPI
}
func (c *Client) JgDataReportOfflineAccountAPI() *api.JgDataReportOfflineAccountAPIService {
	return c.ApiClient.JgDataReportOfflineAccountAPI
}
func (c *Client) JgDataReportRealtimeAccountAPI() *api.JgDataReportRealtimeAccountAPIService {
	return c.ApiClient.JgDataReportRealtimeAccountAPI
}
func (c *Client) JgHistoryListAPI() *api.JgHistoryListAPIService {
	return c.ApiClient.JgHistoryListAPI
}

func (c *Client) CommonApi() *api.CommonApiService {
	return c.ApiClient.CommonApi
}

func (c *Client) SetHost(host string) {
	c.ApiClient.Cfg.Host = host
}

func (c *Client) Use(mws ...api.Middleware) {
	c.ApiClient.Use(mws...)
}

func (c *Client) AddDefaultHeader(key string, value string) {
	c.ApiClient.Cfg.AddDefaultHeader(key, value)
}

func (c *Client) SetDebug(enable bool) {
	c.ApiClient.Cfg.Debug = enable
}