/*
小红书

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgAccountOrderInfoPostRequest struct for JgAccountOrderInfoPostRequest
type JgAccountOrderInfoPostRequest struct {
	// 开始时间
	StartTime string `json:"start_time"`
	// 结束时间
	EndTime string `json:"end_time"`
	// 第几页
	Page int64 `json:"page"`
	// 页大小
	PageSize int64 `json:"page_size"`
	// 品牌方ID
	AdvertiserId int64 `json:"advertiser_id"`
	// 资金账户类型
	AccountTypes []AccountOrderAccountType `json:"account_types,omitempty"`
	Type *AccountOrderType `json:"type,omitempty"`
}

type _JgAccountOrderInfoPostRequest JgAccountOrderInfoPostRequest


