/*
小红书AD

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgAccountAdOrderInfoResponseData struct for JgAccountAdOrderInfoResponseData
type JgAccountAdOrderInfoResponseData struct {
	Total int64 `json:"total"`
	Spend int64 `json:"spend"`
	AdCampaignTradeDetail []JgAccountAdOrderInfoResponseDataAdCampaignTradeDetailInner `json:"ad_campaign_trade_detail"`
}

type _JgAccountAdOrderInfoResponseData JgAccountAdOrderInfoResponseData


