/*
小红书AD

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgDataReportRealtimeAccountResponseData struct for JgDataReportRealtimeAccountResponseData
type JgDataReportRealtimeAccountResponseData struct {
	MessageConsult string `json:"message_consult"`
	ClkLiveRoomRgmv string `json:"clk_live_room_rgmv"`
	ClkLiveEntryPvCost string `json:"clk_live_entry_pv_cost"`
	ExternalRgmv7 string `json:"external_rgmv_7"`
	InvokeAppOpenCnt string `json:"invoke_app_open_cnt"`
	AppPayAmount string `json:"app_pay_amount"`
	ExternalGoodsOrderRate7 string `json:"external_goods_order_rate_7"`
	JdActiveUserNumCvr string `json:"jd_active_user_num_cvr"`
	ExternalGoodsOrder7 string `json:"external_goods_order_7"`
	ExternalLeadsCpl string `json:"external_leads_cpl"`
	AppActivateAmount1dRoi string `json:"app_activate_amount_1d_roi"`
	Message string `json:"message"`
	WechatCopySuccCnt string `json:"wechat_copy_succ_cnt"`
	ClkLiveComment string `json:"clk_live_comment"`
	ExternalGoodsOrder30 string `json:"external_goods_order_30"`
	AppActivateAmount7d string `json:"app_activate_amount_7d"`
	FirstAppPayCtr string `json:"first_app_pay_ctr"`
	Roi string `json:"roi"`
	SellerVisit string `json:"seller_visit"`
	LiveAverageOrderCost string `json:"live_average_order_cost"`
	WechatCopyCnt string `json:"wechat_copy_cnt"`
	ExternalGoodsOrderPrice15 string `json:"external_goods_order_price_15"`
	ClkLive5sEntryPv string `json:"clk_live_5s_entry_pv"`
	ExternalGoodsVisitPrice7 string `json:"external_goods_visit_price_7"`
	LeadsButtonImpression string `json:"leads_button_impression"`
	MsgLeadsCost string `json:"msg_leads_cost"`
	ExternalGoodsVisitPrice24h string `json:"external_goods_visit_price_24h"`
	ExternalGoodsVisitRate24h string `json:"external_goods_visit_rate_24h"`
	AppActivateAmount3dRoi string `json:"app_activate_amount_3d_roi"`
	SearchCmtClick string `json:"search_cmt_click"`
	Impression string `json:"impression"`
	ExternalRoi15 string `json:"external_roi_15"`
	AppKeyActionCost string `json:"app_key_action_cost"`
	Retention3dCnt string `json:"retention_3d_cnt"`
	ClickOrderCvr string `json:"click_order_cvr"`
	ClkLiveRoomRoi string `json:"clk_live_room_roi"`
	InvokeAppEnterStoreCnt string `json:"invoke_app_enter_store_cnt"`
	InvokeAppPaymentCost string `json:"invoke_app_payment_cost"`
	Acp string `json:"acp"`
	ShoppingCartAdd string `json:"shopping_cart_add"`
	ClkLiveEntryPv string `json:"clk_live_entry_pv"`
	ClkLiveAvgViewTime string `json:"clk_live_avg_view_time"`
	PurchaseOrderPrice7d string `json:"purchase_order_price_7d"`
	ValidLeadsCpl string `json:"valid_leads_cpl"`
	PresaleOrderNum7d string `json:"presale_order_num_7d"`
	ExternalLeads string `json:"external_leads"`
	ExternalGoodsVisitRate7 string `json:"external_goods_visit_rate_7"`
	AppKeyActionCnt string `json:"app_key_action_cnt"`
	AppPayCnt7d string `json:"app_pay_cnt_7d"`
	ValidLeads string `json:"valid_leads"`
	SearchInvokeButtonClickCost string `json:"search_invoke_button_click_cost"`
	AppDownloadButtonClickCost string `json:"app_download_button_click_cost"`
	AppActivateCnt string `json:"app_activate_cnt"`
	IdentityCertiCnt string `json:"identity_certi_cnt"`
	ExternalGoodsOrderPrice7 string `json:"external_goods_order_price_7"`
	FirstAppPayCnt string `json:"first_app_pay_cnt"`
	CurrentAppPayCnt string `json:"current_app_pay_cnt"`
	PicSave string `json:"pic_save"`
	ReservePv string `json:"reserve_pv"`
	AppDownloadButtonClickCnt string `json:"app_download_button_click_cnt"`
	Cpm string `json:"cpm"`
	SearchCmtClickCvr string `json:"search_cmt_click_cvr"`
	SearchCmtAfterReadAvg string `json:"search_cmt_after_read_avg"`
	Ctr string `json:"ctr"`
	Comment string `json:"comment"`
	GoodsOrder string `json:"goods_order"`
	SuccessGoodsOrder string `json:"success_goods_order"`
	GoodsOrderPrice string `json:"goods_order_price"`
	ClkLiveRoomOrderNum string `json:"clk_live_room_order_num"`
	AddCartPrice string `json:"add_cart_price"`
	Follow string `json:"follow"`
	GoodsVisit string `json:"goods_visit"`
	LeadsCpl string `json:"leads_cpl"`
	MessageUser string `json:"message_user"`
	InitiativeMessageCpl string `json:"initiative_message_cpl"`
	PhoneCallCnt string `json:"phone_call_cnt"`
	ActionButtonCtr string `json:"action_button_ctr"`
	GoodsVisitPrice string `json:"goods_visit_price"`
	Leads string `json:"leads"`
	JdActiveUserNum string `json:"jd_active_user_num"`
	Share string `json:"share"`
	ExternalRoi7 string `json:"external_roi_7"`
	AppRegisterCtr string `json:"app_register_ctr"`
	Collect string `json:"collect"`
	Screenshot string `json:"screenshot"`
	AppRegisterCnt string `json:"app_register_cnt"`
	AppActivateAmount3d string `json:"app_activate_amount_3d"`
	Retention7dCnt string `json:"retention_7d_cnt"`
	Click string `json:"click"`
	InvokeAppPaymentCnt string `json:"invoke_app_payment_cnt"`
	Retention1dCnt string `json:"retention_1d_cnt"`
	Interaction string `json:"interaction"`
	LandingPageVisit string `json:"landing_page_visit"`
	ExternalGoodsOrder15 string `json:"external_goods_order_15"`
	InvokeAppPaymentRoi string `json:"invoke_app_payment_roi"`
	AppActivateCtr string `json:"app_activate_ctr"`
	ExternalGoodsVisit24h string `json:"external_goods_visit_24h"`
	SearchInvokeButtonClickCnt string `json:"search_invoke_button_click_cnt"`
	Fee string `json:"fee"`
	MessageConsultCpl string `json:"message_consult_cpl"`
	ExternalRoi30 string `json:"external_roi_30"`
	JdActiveUserNumCpl string `json:"jd_active_user_num_cpl"`
	CommodityBuyCnt string `json:"commodity_buy_cnt"`
	ExternalRgmv15 string `json:"external_rgmv_15"`
	InvokeAppEngagementCost string `json:"invoke_app_engagement_cost"`
	AppDownloadButtonClickCtr string `json:"app_download_button_click_ctr"`
	CurrentAppPayCost string `json:"current_app_pay_cost"`
	SellerVisitPrice string `json:"seller_visit_price"`
	InitiativeMessage string `json:"initiative_message"`
	ExternalGoodsOrderRate15 string `json:"external_goods_order_rate_15"`
	InvokeAppPaymentAmount string `json:"invoke_app_payment_amount"`
	FirstAppPayCost string `json:"first_app_pay_cost"`
	ExternalGoodsOrderRate30 string `json:"external_goods_order_rate_30"`
	AppPayCost7d string `json:"app_pay_cost_7d"`
	Like string `json:"like"`
	Cpi string `json:"cpi"`
	ActionButtonClick string `json:"action_button_click"`
	PresaleOrderGmv7d string `json:"presale_order_gmv_7d"`
	InvokeAppOpenCost string `json:"invoke_app_open_cost"`
	InvokeAppEnterStoreCost string `json:"invoke_app_enter_store_cost"`
	InvokeAppPaymentUnitPrice string `json:"invoke_app_payment_unit_price"`
	AppActivateAmount1d string `json:"app_activate_amount_1d"`
	ClkLiveAllFollow string `json:"clk_live_all_follow"`
	MsgLeadsNum string `json:"msg_leads_num"`
	ClkLive5sEntryUvCost string `json:"clk_live_5s_entry_uv_cost"`
	InvokeAppEngagementCnt string `json:"invoke_app_engagement_cnt"`
	AppRegisterCost string `json:"app_register_cost"`
	AppKeyActionCtr string `json:"app_key_action_ctr"`
	AppPayRoi string `json:"app_pay_roi"`
	Rgmv string `json:"rgmv"`
	ExternalRgmv30 string `json:"external_rgmv_30"`
	ExternalGoodsOrderPrice30 string `json:"external_goods_order_price_30"`
	PurchaseOrderGmv7d string `json:"purchase_order_gmv_7d"`
	AppActivateCost string `json:"app_activate_cost"`
	AppActivateAmount7dRoi string `json:"app_activate_amount_7d_roi"`
	LeadsCvr string `json:"leads_cvr"`
	SearchCmtAfterRead string `json:"search_cmt_after_read"`
	PhoneCallSuccCnt string `json:"phone_call_succ_cnt"`
	PurchaseOrderRoi7d string `json:"purchase_order_roi_7d"`
	ExternalGoodsVisit7 string `json:"external_goods_visit_7"`
}

type _JgDataReportRealtimeAccountResponseData JgDataReportRealtimeAccountResponseData


