/*
小红书AD

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgHistoryListResponse struct for JgHistoryListResponse
type JgHistoryListResponse struct {
	Code int64 `json:"code"`
	Success bool `json:"success"`
	Msg string `json:"msg"`
	RequestId *string `json:"request_id,omitempty"`
	Data JgHistoryListResponseData `json:"data"`
}

type _JgHistoryListResponse JgHistoryListResponse


