/*
小红书AD

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgAccountAdOrderInfoPostRequest struct for JgAccountAdOrderInfoPostRequest
type JgAccountAdOrderInfoPostRequest struct {
	// 开始时间 yyyy-mm-dd
	StartTime string `json:"start_time"`
	// 结束时间 yyyy-mm-dd
	EndTime string `json:"end_time"`
	// 第几页
	Page int64 `json:"page"`
	// 页大小
	PageSize int64 `json:"page_size"`
	// 品牌方ID 
	AdvertiserId int64 `json:"advertiser_id"`
}

type _JgAccountAdOrderInfoPostRequest JgAccountAdOrderInfoPostRequest


