/*
小红书AD

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgHistoryListPostRequest struct for JgHistoryListPostRequest
type JgHistoryListPostRequest struct {
	// 开始时间 格式需为yyyy-mm-dd
	StartTime string `json:"start_time"`
	// 结束时间 格式需为yyyy-mm-dd
	EndTime string `json:"end_time"`
	// 品牌方ID
	AdvertiserId int64 `json:"advertiser_id"`
	// 第几页 默认为1
	Page *int64 `json:"page,omitempty"`
	// 页大小 默认为20，最大50
	PageSize *int64 `json:"page_size,omitempty"`
	// 操作对象名称
	Name *string `json:"name,omitempty"`
	// 操作内容
	OptType *int64 `json:"opt_type,omitempty"`
	// 操作层级
	Level *int64 `json:"level,omitempty"`
	// 操作对象ID 仅当操作层级为计划、单元、创意、关键词时可传值 最多50个
	Ids []int64 `json:"ids,omitempty"`
}

type _JgHistoryListPostRequest JgHistoryListPostRequest


