/*
小红书

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgAccountOrderInfoResponse struct for JgAccountOrderInfoResponse
type JgAccountOrderInfoResponse struct {
	Success bool `json:"success"`
	Msg string `json:"msg"`
	RequestId *string `json:"request_id,omitempty"`
	Data JgAccountOrderInfoResponseData `json:"data"`
	Code int64 `json:"code"`
}

type _JgAccountOrderInfoResponse JgAccountOrderInfoResponse


