/*
小红书AD

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgHistoryListResponseDataHistoryListInner struct for JgHistoryListResponseDataHistoryListInner
type JgHistoryListResponseDataHistoryListInner struct {
	OptTime string `json:"opt_time"`
	OptObjectId string `json:"opt_object_id"`
	OptIp string `json:"opt_ip"`
	OptObject string `json:"opt_object"`
	OptTypeName string `json:"opt_type_name"`
	OldValue string `json:"old_value"`
	NewValue string `json:"new_value"`
	Id int64 `json:"id"`
	OptAccountName string `json:"opt_account_name"`
	OptLevelName string `json:"opt_level_name"`
}

type _JgHistoryListResponseDataHistoryListInner JgHistoryListResponseDataHistoryListInner


