/*
小红书

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgAccountOrderInfoResponseDataAccountTradeDetailInner struct for JgAccountOrderInfoResponseDataAccountTradeDetailInner
type JgAccountOrderInfoResponseDataAccountTradeDetailInner struct {
	LaunchDate *string `json:"launch_date,omitempty"`
	OrderAmount *int64 `json:"order_amount,omitempty"`
	AccountTypeName *string `json:"account_type_name,omitempty"`
	Balance *int64 `json:"balance,omitempty"`
	TransferObject *string `json:"transfer_object,omitempty"`
	Remark *string `json:"remark,omitempty"`
	AccountType *int64 `json:"account_type,omitempty"`
	BusinessTypeName *string `json:"business_type_name,omitempty"`
	OperateType *int64 `json:"operate_type,omitempty"`
	TradeTime *string `json:"trade_time,omitempty"`
	AccountName *string `json:"account_name,omitempty"`
}


