/*
小红书AD

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgAccountAdOrderInfoResponse struct for JgAccountAdOrderInfoResponse
type JgAccountAdOrderInfoResponse struct {
	Msg string `json:"msg"`
	Data JgAccountAdOrderInfoResponseData `json:"data"`
	RequestId *string `json:"request_id,omitempty"`
	Code int64 `json:"code"`
	Success bool `json:"success"`
}

type _JgAccountAdOrderInfoResponse JgAccountAdOrderInfoResponse


