/*
小红书AD

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgAccountBudgetInfoResponse struct for JgAccountBudgetInfoResponse
type JgAccountBudgetInfoResponse struct {
	Success bool `json:"success"`
	Msg string `json:"msg"`
	Data JgAccountBudgetInfoResponseData `json:"data"`
	RequestId *string `json:"request_id,omitempty"`
	Code int64 `json:"code"`
}

type _JgAccountBudgetInfoResponse JgAccountBudgetInfoResponse


