/*
小红书

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgAccountOrderInfoResponseData struct for JgAccountOrderInfoResponseData
type JgAccountOrderInfoResponseData struct {
	AccountTradeDetail []JgAccountOrderInfoResponseDataAccountTradeDetailInner `json:"account_trade_detail"`
	TotalCount int64 `json:"total_count"`
	AggregateOrder int64 `json:"aggregate_order"`
}

type _JgAccountOrderInfoResponseData JgAccountOrderInfoResponseData


