/*
小红书

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgDataReportOfflineAccountResponse struct for JgDataReportOfflineAccountResponse
type JgDataReportOfflineAccountResponse struct {
	RequestId *string `json:"request_id,omitempty"`
	Code int64 `json:"code"`
	Success bool `json:"success"`
	Msg string `json:"msg"`
	Data JgDataReportOfflineAccountResponseData `json:"data"`
}

type _JgDataReportOfflineAccountResponse JgDataReportOfflineAccountResponse


