/*
小红书

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgDataReportOfflineAccountResponseDataDataListInner struct for JgDataReportOfflineAccountResponseDataDataListInner
type JgDataReportOfflineAccountResponseDataDataListInner struct {
	Screenshot string `json:"screenshot"`
	LandingPageVisit string `json:"landing_page_visit"`
	SearchCmtClickCvr string `json:"search_cmt_click_cvr"`
	InvokeAppOpenCost string `json:"invoke_app_open_cost"`
	Time string `json:"time"`
	Collect string `json:"collect"`
	ActionButtonClick string `json:"action_button_click"`
	LeadsCpl string `json:"leads_cpl"`
	LeadsButtonImpression string `json:"leads_button_impression"`
	AddCartPrice string `json:"add_cart_price"`
	ExternalGoodsOrderPrice30 string `json:"external_goods_order_price_30"`
	MessageUser string `json:"message_user"`
	InvokeAppPaymentCnt string `json:"invoke_app_payment_cnt"`
	TiUserNum string `json:"ti_user_num"`
	Follow string `json:"follow"`
	ClkLiveRoomRgmv string `json:"clk_live_room_rgmv"`
	ClkLiveComment string `json:"clk_live_comment"`
	ExternalGoodsOrderRate30 string `json:"external_goods_order_rate_30"`
	Message string `json:"message"`
	InvokeAppPaymentCost string `json:"invoke_app_payment_cost"`
	Acp string `json:"acp"`
	SellerVisit string `json:"seller_visit"`
	AddWechatSucCost string `json:"add_wechat_suc_cost"`
	Impression string `json:"impression"`
	GoodsOrder string `json:"goods_order"`
	SellerVisitPrice string `json:"seller_visit_price"`
	ClkLiveAvgViewTime string `json:"clk_live_avg_view_time"`
	ClkLiveRoomRoi string `json:"clk_live_room_roi"`
	ExternalGoodsOrderRate15 string `json:"external_goods_order_rate_15"`
	InvokeAppOpenCnt string `json:"invoke_app_open_cnt"`
	SearchCmtAfterReadAvg string `json:"search_cmt_after_read_avg"`
	ExternalRoi30 string `json:"external_roi_30"`
	Like string `json:"like"`
	ActionButtonCtr string `json:"action_button_ctr"`
	PicSave string `json:"pic_save"`
	ExternalGoodsOrder15 string `json:"external_goods_order_15"`
	ExternalGoodsOrderPrice15 string `json:"external_goods_order_price_15"`
	InvokeAppPaymentUnitPrice string `json:"invoke_app_payment_unit_price"`
	Cpi string `json:"cpi"`
	SearchCmtAfterRead string `json:"search_cmt_after_read"`
	ExternalRgmv15 string `json:"external_rgmv_15"`
	SearchInvokeButtonClickCost string `json:"search_invoke_button_click_cost"`
	ExternalGoodsVisitPrice7 string `json:"external_goods_visit_price_7"`
	TiUserPrice string `json:"ti_user_price"`
	Fee string `json:"fee"`
	ReservePv string `json:"reserve_pv"`
	MsgLeadsNum string `json:"msg_leads_num"`
	PurchaseOrderPrice7d string `json:"purchase_order_price_7d"`
	AddWechatCount string `json:"add_wechat_count"`
	MessageReplyIn1minRate string `json:"message_reply_in_1min_rate"`
	ClkLiveEntryPv string `json:"clk_live_entry_pv"`
	ExternalGoodsVisitRate7 string `json:"external_goods_visit_rate_7"`
	InvokeAppEnterStoreCost string `json:"invoke_app_enter_store_cost"`
	JdActiveUserNumCvr string `json:"jd_active_user_num_cvr"`
	InvokeAppPaymentRoi string `json:"invoke_app_payment_roi"`
	ShopPoiPageNavigateClick string `json:"shop_poi_page_navigate_click"`
	FstMessageReplyIn45sRate string `json:"fst_message_reply_in_45s_rate"`
	ClkLiveAllFollow string `json:"clk_live_all_follow"`
	SearchInvokeButtonClickCnt string `json:"search_invoke_button_click_cnt"`
	Leads string `json:"leads"`
	ExternalGoodsOrderRate7 string `json:"external_goods_order_rate_7"`
	IUserPrice string `json:"i_user_price"`
	ShoppingCartAdd string `json:"shopping_cart_add"`
	Roi string `json:"roi"`
	InitiativeMessage string `json:"initiative_message"`
	MessageReplyIn30sRate string `json:"message_reply_in_30s_rate"`
	GoodsVisit string `json:"goods_visit"`
	GoodsVisitPrice string `json:"goods_visit_price"`
	PresaleOrderGmv7d string `json:"presale_order_gmv_7d"`
	Placement string `json:"placement"`
	ExternalRgmv30 string `json:"external_rgmv_30"`
	ClickOrderCvr string `json:"click_order_cvr"`
	LiveAverageOrderCost string `json:"live_average_order_cost"`
	ShopPoiPageVisitPrice string `json:"shop_poi_page_visit_price"`
	WechatTalkCount string `json:"wechat_talk_count"`
	ClkLiveRoomOrderNum string `json:"clk_live_room_order_num"`
	ExternalRoi15 string `json:"external_roi_15"`
	PurchaseOrderRoi7d string `json:"purchase_order_roi_7d"`
	AddWechatSucCount string `json:"add_wechat_suc_count"`
	SearchCmtClick string `json:"search_cmt_click"`
	ExternalGoodsOrder7 string `json:"external_goods_order_7"`
	ShopPoiPagePv string `json:"shop_poi_page_pv"`
	Ctr string `json:"ctr"`
	SuccessGoodsOrder string `json:"success_goods_order"`
	ValidLeadsCpl string `json:"valid_leads_cpl"`
	MsgLeadsCost string `json:"msg_leads_cost"`
	ExternalRgmv7 string `json:"external_rgmv_7"`
	InitiativeMessageCpl string `json:"initiative_message_cpl"`
	ClkLiveEntryPvCost string `json:"clk_live_entry_pv_cost"`
	ExternalGoodsOrder30 string `json:"external_goods_order_30"`
	InvokeAppEngagementCnt string `json:"invoke_app_engagement_cnt"`
	Cpm string `json:"cpm"`
	Share string `json:"share"`
	MessageFstReplyTimeAvg string `json:"message_fst_reply_time_avg"`
	MessageReplyIn3minRate string `json:"message_reply_in_3min_rate"`
	MessageConsultCpl string `json:"message_consult_cpl"`
	ShopPoiClickNum string `json:"shop_poi_click_num"`
	WechatTalkCost string `json:"wechat_talk_cost"`
	Comment string `json:"comment"`
	ExternalRoi7 string `json:"external_roi_7"`
	PurchaseOrderGmv7d string `json:"purchase_order_gmv_7d"`
	InvokeAppEngagementCost string `json:"invoke_app_engagement_cost"`
	JdActiveUserNum string `json:"jd_active_user_num"`
	ValidLeads string `json:"valid_leads"`
	LeadsCvr string `json:"leads_cvr"`
	InvokeAppPaymentAmount string `json:"invoke_app_payment_amount"`
	Interaction string `json:"interaction"`
	GoodsOrderPrice string `json:"goods_order_price"`
	ExternalGoodsOrderPrice7 string `json:"external_goods_order_price_7"`
	InvokeAppEnterStoreCnt string `json:"invoke_app_enter_store_cnt"`
	JdActiveUserNumCpl string `json:"jd_active_user_num_cpl"`
	ExternalGoodsVisit7 string `json:"external_goods_visit_7"`
	Click string `json:"click"`
	AddWechatCost string `json:"add_wechat_cost"`
	IUserNum string `json:"i_user_num"`
	Rgmv string `json:"rgmv"`
	MessageConsult string `json:"message_consult"`
	PresaleOrderNum7d string `json:"presale_order_num_7d"`
}

type _JgDataReportOfflineAccountResponseDataDataListInner JgDataReportOfflineAccountResponseDataDataListInner


