/*
小红书

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
    "fmt"
)
// AccountOrderAccountType 0-现金;1-常规返货;2-授信;6-赔付返货;不传，默认值为[0,1,2,6]
type AccountOrderAccountType int64

// List of AccountOrderAccountType
const (
	AccountOrderAccountType__0 = 0
	AccountOrderAccountType__1 = 1
	AccountOrderAccountType__2 = 2
	AccountOrderAccountType__6 = 6
)

// All allowed values of AccountOrderAccountType enum
var AllowedAccountOrderAccountTypeEnumValues = []AccountOrderAccountType{
	0,
	1,
	2,
	6,
}

// NewAccountOrderAccountTypeFromValue returns a pointer to a valid AccountOrderAccountType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAccountOrderAccountTypeFromValue(v int64) (*AccountOrderAccountType, error) {
	ev := AccountOrderAccountType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AccountOrderAccountType: valid values are %v", v, AllowedAccountOrderAccountTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AccountOrderAccountType) IsValid() bool {
	for _, existing := range AllowedAccountOrderAccountTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AccountOrderAccountType value
func (v AccountOrderAccountType) Ptr() *AccountOrderAccountType {
	return &v
}


