/*
小红书

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgAccountBudgetInfoPostRequest struct for JgAccountBudgetInfoPostRequest
type JgAccountBudgetInfoPostRequest struct {
	// 品牌方ID
	AdvertiserId int64 `json:"advertiser_id"`
}

type _JgAccountBudgetInfoPostRequest JgAccountBudgetInfoPostRequest


