/*
小红书AD

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgHistoryListResponseData struct for JgHistoryListResponseData
type JgHistoryListResponseData struct {
	TotalPage int64 `json:"total_page"`
	HistoryList []JgHistoryListResponseDataHistoryListInner `json:"history_list"`
	Total int64 `json:"total"`
}

type _JgHistoryListResponseData JgHistoryListResponseData


