/*
小红书AD

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgAccountAdOrderInfoResponseDataAdCampaignTradeDetailInner struct for JgAccountAdOrderInfoResponseDataAdCampaignTradeDetailInner
type JgAccountAdOrderInfoResponseDataAdCampaignTradeDetailInner struct {
	PayTime *string `json:"pay_time,omitempty"`
	CampaignDayBudget *int64 `json:"campaign_day_budget,omitempty"`
	OrderAmount *int64 `json:"order_amount,omitempty"`
	CampaignId *int64 `json:"campaign_id,omitempty"`
	CampaignName *string `json:"campaign_name,omitempty"`
	LaunchDate *string `json:"launch_date,omitempty"`
}


