/*
小红书

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgDataReportRealtimeAccountPostRequest struct for JgDataReportRealtimeAccountPostRequest
type JgDataReportRealtimeAccountPostRequest struct {
	AdvertiserId int64 `json:"advertiser_id"`
	StartDate string `json:"start_date"`
	EndDate string `json:"end_date"`
	PageNum *int64 `json:"page_num,omitempty"`
	PageSize *int64 `json:"page_size,omitempty"`
}

type _JgDataReportRealtimeAccountPostRequest JgDataReportRealtimeAccountPostRequest


