/*
小红书

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
    "fmt"
)
// AccountOrderType 2-服务商
type AccountOrderType int64

// List of AccountOrderType
const (
	AccountOrderType__2 = 2
)

// All allowed values of AccountOrderType enum
var AllowedAccountOrderTypeEnumValues = []AccountOrderType{
	2,
}

// NewAccountOrderTypeFromValue returns a pointer to a valid AccountOrderType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAccountOrderTypeFromValue(v int64) (*AccountOrderType, error) {
	ev := AccountOrderType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AccountOrderType: valid values are %v", v, AllowedAccountOrderTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AccountOrderType) IsValid() bool {
	for _, existing := range AllowedAccountOrderTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AccountOrderType value
func (v AccountOrderType) Ptr() *AccountOrderType {
	return &v
}


