/*
小红书AD

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// JgAccountBudgetInfoResponseData struct for JgAccountBudgetInfoResponseData
type JgAccountBudgetInfoResponseData struct {
	CashBalance *int64 `json:"cash_balance,omitempty"`
	ReturnBalance *int64 `json:"return_balance,omitempty"`
	CreditBalance *int64 `json:"credit_balance,omitempty"`
	AccountBudget *int64 `json:"account_budget,omitempty"`
	LimitDayBudget *int64 `json:"limit_day_budget,omitempty"`
	TotalBalance *int64 `json:"total_balance,omitempty"`
	FreezeBalance *int64 `json:"freeze_balance,omitempty"`
	AvailableBalance *int64 `json:"available_balance,omitempty"`
	TodaySpend *int64 `json:"today_spend,omitempty"`
	CompensateReturnBalance *int64 `json:"compensate_return_balance,omitempty"`
}


